website/auth.py
from flask import Blueprint,request,flash,redirect,render_template,url_for
from .models import db, User, Sponsor,Influencer
from flask_login import login_required, current_user,login_user,logout_user
from werkzeug.security import generate_password_hash,check_password_hash


auth = Blueprint('auth', __name__)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out', category='success')
    return redirect(url_for('views.home'))

@auth.route('/signup_sponsor', methods=['GET','POST'])
def signup_sponsor():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        industry = request.form.get('industry')
        budget = request.form.get('budget')
        password = request.form.get('password') 
        confirm_password = request.form.get('confirm_password')
        
        user = User.query.filter_by(email = email).first()
        if user:
            flash('User already exists',category='error')
        elif password != confirm_password:
            flash('Confirm password should match password',category='error')
        else:
            new_user = User(email = email, password = generate_password_hash(password,method='pbkdf2:sha256'), role = 'sponsor', flagged='False')
            new_sponsor = Sponsor(name=name, industry=industry, budget=budget)
            new_sponsor.user = new_user
            db.session.add(new_user)
            db.session.add(new_sponsor)
            db.session.commit()
            
            login_user(new_user, remember=True)
            
            flash('Account created successfully', category='success')
            return redirect(url_for('views.sponsor_dashboard'))
            
    return render_template('signup.html', user_type = 'sponsor', user = current_user)



@auth.route('/signup_influencer', methods=['GET','POST'])
def signup_influencer():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        category = request.form.get('category')
        niche = request.form.get('niche')
        reach = request.form.get('reach')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        
        user = User.query.filter_by(email = email).first()
        if user:
            flash('User already exists',category='error')
        elif password != confirm_password:
            flash('Confirm password should match password',category='error')
        else:
            new_user = User(email = email, password = generate_password_hash(password,method='pbkdf2:sha256'), role = 'influencer',flagged='False')
            new_influencer = Influencer(name = name, category = category, niche = niche, reach= reach)
            new_influencer.user = new_user
            db.session.add(new_user)
            db.session.add(new_influencer)
            db.session.commit()
            
            login_user(new_user, remember=True)
            
            flash('Account created successfully', category='success')
            return redirect(url_for('views.influencer_dashboard'))
            
    return render_template('signup.html',user = current_user, user_type = 'influencer')

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email = email).first()
        
        if user:
            if user.role == 'admin':
                if password == '123456789':
                    login_user(user, remember=True)
                    flash('Logged in successfully', category='success')
                    return redirect(url_for('views.admin_dashboard'))
                else:
                    flash('Incorrect password', category='error')
                    return redirect(url_for('auth.login'))
                
            if user.flagged == 'True':
                flash('Your account has been flagged. Please contact admin', category='error')
                return redirect(url_for('auth.login'))
            elif check_password_hash(user.password, password):
                login_user(user, remember=True)
                flash('Logged in successfully', category='success')
                if user.role == 'sponsor':
                    return redirect(url_for('views.sponsor_dashboard'))
                elif user.role == 'influencer':
                    return redirect(url_for('views.influencer_dashboard'))
                elif user.role == 'admin':
                    return redirect(url_for('views.admin_dashboard'))
            else:
                flash('Incorrect password', category='error')
                return redirect(url_for('auth.login'))
        else:
            flash('User does not exist, Signup now', category='error')
            return redirect(url_for('auth.login'))
    return render_template('login.html',user = current_user)

website/views.py
from flask import Blueprint,render_template,request,flash,redirect,url_for
from sqlalchemy import desc
from flask_login import current_user,login_required
from .models import *
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime


views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('home.html', user = current_user)


### SPONSOR ROUTES ###
@views.route('sponsor/dashboard')
@login_required
def sponsor_dashboard():
    sponsor = Sponsor.query.get(current_user.id)
    campaigns = [campaign for campaign in sponsor.campaigns if (campaign.end_date > datetime.now().date()) and (campaign.start_date < datetime.now().date()) and (campaign.flagged == 'False')]
    current_date = datetime.now().date()
    
    new_nego = Negotiation.query.filter_by(sponsor_id=sponsor.id).all()
    return render_template('sponsor_dashboard.html', user = current_user, sponsor=sponsor, campaigns=campaigns,current_date=current_date, new_nego=new_nego)

@views.route('sponsor/profile',  methods=['GET', 'POST'])
@login_required
def sponsor_profile():
    sponsor = Sponsor.query.get(current_user.id)
    if request.method == 'POST':
        flag = True
        sponsor.name = request.form['name']
        sponsor.industry = request.form['industry']
        if request.form['budget']:
            sponsor.budget = float(request.form['budget'])
        db.session.commit()
        
        current_password = request.form.get('current_password')
        if current_password != "":
            new_password = request.form.get('new_password')
            if check_password_hash(current_user.password, current_password):
                current_user.password = generate_password_hash(new_password)
                db.session.commit()
            else:
                flash('Incorrect password', category='error')
                flag = False
        if flag:
            flash('Profile Updated', category='success')
            return render_template('sponsor_profile.html', user = current_user, sponsor = sponsor)
    return render_template('sponsor_profile.html', sponsor=sponsor, user = current_user)

@views.route('sponsor/campaigns',  methods=['GET', 'POST'])
@login_required
def sponsor_campaigns():
    sponsor = Sponsor.query.get(current_user.id)
    query = Campaign.query
    query = query.filter( Campaign.sponsor_id == sponsor.id)
    running_camp = query.filter( Campaign.end_date > datetime.now().date())
    noflag_campaigns = running_camp.filter_by( flagged = 'False').all()
    flag_campaigns = running_camp.filter_by( flagged = 'True').all()

    if request.method == 'POST':
        campaign_name_filter = request.form.get('campaign_filter')
        if campaign_name_filter:
            noflag_campaigns = [campaign for campaign in noflag_campaigns if campaign_name_filter.lower() in campaign.name.lower()]
            flag_campaigns = [campaign for campaign in flag_campaigns if campaign_name_filter.lower() in campaign.name.lower()]
            return render_template('campaigns.html', user=current_user, noflag_campaigns=noflag_campaigns, flag_campaigns=flag_campaigns)
        else:
            return render_template('campaigns.html', user=current_user, noflag_campaigns=noflag_campaigns, flag_campaigns=flag_campaigns)
            
    return render_template('campaigns.html', user=current_user, noflag_campaigns=noflag_campaigns, flag_campaigns=flag_campaigns)

@views.route('/sponsor/campaign/add', methods=['POST'])
def create_campaign():
    name = request.form['name']
    description = request.form.get('description')
    startDate_str = request.form.get('startDate')
    endDate_str = request.form.get('endDate')
    budget = request.form.get('budget')
    visibility = request.form.get('visibility')
    
    start_date = datetime.strptime(startDate_str, '%Y-%m-%d').date()
    end_date = datetime.strptime(endDate_str, '%Y-%m-%d').date()
    
    new_campaign = Campaign(name=name, description=description, start_date=start_date, end_date=end_date, budget=budget, visibility=visibility,flagged='False', sponsor_id=current_user.id)
    db.session.add(new_campaign)
    db.session.commit()

    flash('Campaign created successfully', category='success')
    return redirect('/sponsor/campaigns')
    
@views.route('/sponsor/campaign/delete/<int:campaign_id>', methods=['POST'])
def delete_campaign(campaign_id):
    campaign = Campaign.query.get_or_404(campaign_id)
    ad_requests = AdRequest.query.filter_by(campaign_id=campaign_id).all()
    for ad_request in ad_requests:
        negotiations = Negotiation.query.filter_by(ad_request_id=ad_request.id).all()
        for negotiation in negotiations:
            db.session.delete(negotiation)
        db.session.delete(ad_request)

    db.session.delete(campaign)
    db.session.commit()
    flash('Campaign deleted', category='success')
    return redirect('/sponsor/campaigns')

@views.route('/sponsor/campaign/update/<int:campaign_id>', methods=['POST'])
def update_campaign(campaign_id):
    campaign = Campaign.query.get_or_404(campaign_id)
    
    start_date_str = request.form.get('start_date',campaign.start_date)
    end_date_str = request.form.get('end_date', campaign.end_date)
    
    campaign.name = request.form.get('name')
    campaign.start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
    campaign.end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()
    campaign.budget = float(request.form.get('budget'))
    campaign.visibility = request.form.get('visibility')
    campaign.description = request.form.get('description',campaign.description)

    db.session.commit()
    print('updated')
    flash('Campaign Updated', category='success')
    return redirect(f'/sponsor/campaign/details/{campaign_id}')
    
@views.route('/sponsor/campaign/details/<int:campaign_id>')
@login_required
def campaign_details(campaign_id):
    # Deleting previous negotiation if any
    query = Negotiation.query
    query = query.filter_by(sponsor_id = current_user.sponsor.id)
    query = query.filter(Negotiation.message == 'sponsor_accepted')
    negos = query.all()
    for nego in negos:
        db.session.delete(nego)
    db.session.commit()
    
    campaign = Campaign.query.filter_by(id=campaign_id).first()
    return render_template('campaign_details.html', user=current_user, campaign=campaign)

@views.route('sponsor/stats')
@login_required
def sponsor_stats():
    sponsor = Sponsor.query.get(current_user.id)
    bar_data = [0,0,0]
    for camp in sponsor.campaigns:
        if camp.start_date > datetime.now().date():
            bar_data[0] += 1
        elif camp.start_date <= datetime.now().date() and camp.end_date >= datetime.now().date():
            bar_data[1] += 1
        else:
            bar_data[2] += 1

    return render_template('sponsor_stats.html', user=current_user, sponsor = sponsor, bar_data=bar_data, today_date= datetime.now().date())



@views.route('sponsor/decisions/<int:negotiation_id>', methods=['GET', 'POST'])
@login_required
def sponsor_decisions(negotiation_id):
    negotiation = Negotiation.query.filter_by(id=negotiation_id).first()
    campaign_id = negotiation.ad_request.campaign.id
    if request.method == 'POST':
        form_id = request.form.get('form_id')
        if form_id == 'new_request':
            action = request.form.get('action')
            if action == 'accept':
                if negotiation.sponsor.total_spent:
                    negotiation.sponsor.total_spent += negotiation.proposed_amount
                else:
                    negotiation.sponsor.total_spent = negotiation.proposed_amount
                
                if negotiation.influencer.earning:
                    negotiation.influencer.earning += negotiation.proposed_amount
                else:
                    negotiation.influencer.earning = negotiation.proposed_amount
                    
                negotiation.sponsor.total_spent += negotiation.ad_request.payment_amount
                negotiation.influencer.earning += negotiation.ad_request.payment_amount
                negotiation.ad_request.influencer_id = negotiation.influencer_id
                negotiation.ad_request.status = 'Accepted'
                negotiation.message = 'sponsor_accepted'    
                db.session.commit()  
                          
            elif action == 'reject':
                db.session.delete(negotiation)
                db.session.commit()
                
            else:
                amount = request.form.get('negotiation')
                negotiation.previous_time = negotiation.latest_time
                negotiation.latest_time = datetime.now()
                negotiation.proposed_amount = amount
                negotiation.message = 'sponsor_negotiated'
                db.session.commit()
        return redirect(url_for('views.campaign_details',campaign_id = campaign_id))
    
    
@views.route('/sponsor/update_delete/<int:adrequest_id>',methods=['POST','GET'])
@login_required
def update_delete(adrequest_id):
    ad_request = AdRequest.query.filter_by(id=adrequest_id).first()
    campaign_id = ad_request.campaign_id
    if request.method == 'POST':
        action = request.form.get('action')
        if action == 'update':
            req = request.form.get('requirements',ad_request.requirements)
            amount = request.form.get('amount',ad_request.payment_amount)
            ad_request.requirements = req
            ad_request.payment_amount = amount
            db.session.commit()
            flash('Ad Request updated', category='success')
        if action == 'delete':
            for nego in ad_request.negotiations:
                db.session.delete(nego)
            db.session.delete(ad_request)
            db.session.commit()
            flash('Ad Request deleted', category='success')
            
        return redirect(url_for('views.campaign_details',campaign_id = campaign_id))
            

website/templates/campaigns.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <nav id="sponsor_navbar" class="navbar navbar-expand-lg mt-2" >
            <div class="container-fluid">
                <!-- Toggle button -->
                <button data-mdb-collapse-init class="navbar-toggler" type="button" data-mdb-target="#navbarCenteredExample" aria-controls="navbarCenteredExample" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarCenteredExample">
                    <ul class="nav-links">
                        <li><a href="{{ url_for('views.sponsor_dashboard') }}">Dashboard</a></li>
                        <li class="center"><a href="{{ url_for('views.sponsor_profile') }}">Profile</a></li>
                        <li class="upward"><a href="{{ url_for('views.sponsor_campaigns') }}">Campaigns</a></li>
                        <li class="forward"><a href="{{ url_for('views.sponsor_stats') }}">Stats</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-6">
            <h1>All Campaigns</h1>
        </div>
        <div class="col-md-6 text-right">
            <span><button class="grey-btn" data-bs-toggle="modal" data-bs-target="#createCampaignModal">Create Campaign</button></span>
            <form action="{{ url_for('views.sponsor_campaigns') }}" class="search" method="post">
                <input name="campaign_filter" placeholder="Search..." type="text">
                <button type="submit">Go</button>
            </form>
        </div>
    </div>
    <hr>
    <br>
    <div>
        {% if noflag_campaigns|length == 0 and flag_campaigns|length == 0 %}
            <p><em>No campaigns to display</em></p>
            <br>
        {% else %}
        {% if noflag_campaigns|length != 0 %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for campaign in noflag_campaigns %}
                <div class="col">
                    <a href="{{ url_for('views.campaign_details', campaign_id=campaign.id) }}">
                        <div class="campaign-card">
                            <div>
                                <h3><strong>{{ campaign.name }}</strong></h3>
                                <p>{{ campaign.description }}</p>

                                <p class="text-muted">Click to view details and ad requests.</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <br>
        {% endif %}

        {% if flag_campaigns|length != 0 %}
        <hr>
        <h3>Flagged Campaigns</h3>
        <br>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for campaign in flag_campaigns %}
                <div class="col">
                    <a href="{{ url_for('views.campaign_details', campaign_id=campaign.id) }}">
                        <div class="campaign-card" style="background: rgba(162, 83, 97, 0.262);">
                            <div>
                                <h3><strong>{{ campaign.name }}</strong></h3>
                                <p>{{ campaign.description }}</p>

                                <p class="text-muted">Click to view details</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endif %}
        <br>
    </div>
    <!-- Modals for Campaign Management -->
    <div class="modal fade" id="createCampaignModal" tabindex="-1" aria-labelledby="createCampaignModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createCampaignModalLabel">Create New Campaign</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form name="createCampaign" action="/sponsor/campaign/add" method="post">
                        <div class="mb-3">
                            <label for="name" class="form-label">Campaign Name</label>
                            <input type="text" class="form-control" name="name" id="name" required>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <textarea type="text" placeholder="(Less than 50 words)" class="form-control" name="description" id="description" required></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="startDate" class="form-label">Start Date</label>
                            <input type="date" class="form-control" name="startDate" id="startDate" required>
                        </div>
                        <div class="mb-3">
                            <label for="endDate" class="form-label">End Date</label>
                            <input type="date" class="form-control" name="endDate" id="endDate" required>
                        </div>
                        <div class="mb-3">
                            <label for="budget" class="form-label">Budget</label>
                            <input type="number" class="form-control" name="budget" id="budget" required>
                        </div>
                        <div class="mb-3">
                            <label for="visibility" class="form-label">Visibility</label>
                            <select class="form-select" name="visibility" id="visibility" required>
                                <option value="Public">Public</option>
                                <option value="Private">Private</option>
                            </select>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>  
</div>
{% endblock %}

website/templates/find_influencer.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
       <nav id="sponsor_navbar" class="navbar navbar-expand-lg mt-2" >
            <div class="container-fluid">
                <!-- Toggle button -->
                <button data-mdb-collapse-init class="navbar-toggler" type="button" data-mdb-target="#navbarCenteredExample" aria-controls="navbarCenteredExample" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarCenteredExample">
                    <ul class="nav-links">
                        <li><a href="{{ url_for('views.sponsor_dashboard') }}">Dashboard</a></li>
                        <li class="center"><a href="{{ url_for('views.sponsor_profile') }}">Profile</a></li>
                        <li class="upward"><a href="{{ url_for('views.sponsor_campaigns') }}">Campaigns</a></li>
                        <li class="forward"><a href="{{ url_for('views.sponsor_stats') }}">Stats</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="container mt-3">
        <div class="row">
            <div class="col-md-3">
                <h1>Find Influencer</h1>
            </div>

            <div class="col-md-9 align-item-right">
                  <form class="row gx-3 gy-2 text-right"  action="{{ url_for('views.find_influencer',adrequest_id=adrequest_id) }}" method="post">
                    <div class="col-sm-3">
                        <label class="visually-hidden" for="specificSizeInputName">Name</label>
                        <input type="text" name="name" class="form-control" id="specificSizeInputName" placeholder="Name">
                    </div>
                    <div class="col-sm-3">
                        <label class="visually-hidden" for="specificSizeInputGroupReach">Reach</label>
                        <input type="text" class="form-control" id="specificSizeInputGroupReach" placeholder="Reach Eg. 50-100" name="reach" pattern="^\d+-\d+$" title="Enter range in the format 50-100">
                    </div>
                    <div class="col-sm-3">
                        <label class="visually-hidden" for="specificSizeSelect">Niche</label>
                        <select class="form-select" id="specificSizeSelect" name="niche">
                            <option value="" disabled selected>Niche</option>
                            {% for influencer in influencers %}
                                <option value="{{ influencer.niche }}">{{ influencer.niche }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-dark">Filter</button>
                    </div>
                    <div class="col-auto">
                        <a href="{{ url_for('views.find_influencer',adrequest_id=adrequest_id) }}"><button type="submit" class="btn btn-secondary">Remove filter</button></a>
                    </div>
                </form>
             </div>
        </div>
        <hr>
        <br>

        {% if influencers %}
            <ul class="influencer-display">
                <li class="header">
                    <div class="col-1">Name</div>
                    <div class="col-2">Reach</div>
                    <div class="col-3">Niche</div>
                    <div class="col-4"></div>
                </li>
                {% for influencer in influencers %}
                {% if influencer.user.flagged == 'False' %}
                    <li class="table-row">
                        <div class="col-1">{{ influencer.name }}</div>
                        <div class="col-2">{{ influencer.reach }}</div>
                        <div class="col-3">{{ influencer.niche }}</div>
                        <div class="col-4">
                            <form action="{{ url_for('views.sponsor_send_request',influencer_id=influencer.id,adrequest_id=adrequest_id) }}">
                                <button class="btn btn-secondary">Send Request</button>
                            </form>
                        </div>
                    </li>
                {% endif %}
                {% endfor %}
            </ul>
        {% else %}
            <h4><em>No Influencers Found</em></h4>
        {% endif %}
    </div>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}


{% block content %}
<div class="jumbotron mt-5">
    <div class="container">
      <h1 class="display-3">Welcome!</h1>
      <p>This is a project for Modern Application Development I(MAD 1)</p>
    </div>
</div>
<br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-4 ms-auto">
      <h2><u>Sponsors</u></h2>
      <p>Connect with Top Influencers Today 
        <ul>
            <li>Amplify Your Reach </li>
            <li>Boost Your Brand Visibility</li>
        </ul>
      </p>
      <p>Create and manage different campaigns...</p>
    </div>

    <div class="col-md-4">
      <h2><u>Influencers</u></h2>
      <p>Connect with Top Brands Today 
        <ul>
          <li>Monetize Your Influence </li>
          <li>Turn Followers into Fortune</li>
        </ul>
      </p>
    </div>
  </div>
  <hr>
</div>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-auto">
            
                <form action="{{ url_for('auth.login') }}" method="post" class="box" style="width: 500px;">
                    <h1>Login</h1>
                    <p class="text-muted"> Please enter your login and password!</p>
                    <input type="text" name="email" placeholder="Email">
                    <input type="password" name="password" placeholder="Password">
                    <br>
                    <input type="submit" value="Login">
                    
                </form>
            
        </div>
    </div>
</div>
{% endblock %}

website/templates/sponsor_dashboard.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
       <nav id="sponsor_navbar" class="navbar navbar-expand-lg mt-2" >
            <div class="container-fluid">
                <!-- Toggle button -->
                <button data-mdb-collapse-init class="navbar-toggler" type="button" data-mdb-target="#navbarCenteredExample" aria-controls="navbarCenteredExample" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarCenteredExample">
                    <ul class="nav-links">
                        <li><a href="{{ url_for('views.sponsor_dashboard') }}">Dashboard</a></li>
                        <li class="center"><a href="{{ url_for('views.sponsor_profile') }}">Profile</a></li>
                        <li class="upward"><a href="{{ url_for('views.sponsor_campaigns') }}">Campaigns</a></li>
                        <li class="forward"><a href="{{ url_for('views.sponsor_stats') }}">Stats</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>



    <div class="container mt-3">
        <h1>Welcome {{ user.sponsor.name }}</h1>
        <hr>
        <br>
        <h2>Active Campaigns</h2>
            {% if campaigns %}
            <ul class="campaign-display">
                {% for campaign in campaigns %}
                <li class="row">
                    <div class="col">{{ campaign.name }}</div>
        
                    <div class="col">{{ (campaign.end_date - current_date).days }} days left</div>
                
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p><em>No active campaigns</em></p>
            {% endif %}
        <br>
        <h2>Notifications</h2>
        {% if new_nego %}
            <ul class="notification-display">
                {% for nego in new_nego %}
                {% if nego.message not in ['sponsor_new','sponsor_negotiated'] %}
                    <li class="row" >
                        
                        {% if nego.message == 'influencer_new' %}
                        <div class="col"><strong>New request for {{ nego.ad_request.campaign.name }}</strong></div>
                        {% elif nego.message == 'influencer_negotiated' %}
                        <div class="col"><strong>New amount negotiated for {{ nego.ad_request.campaign.name }}</strong></div>
                        {% endif %}

                        <div class="col text-right"><a href="{{ url_for('views.campaign_details', campaign_id=nego.ad_request.campaign.id) }}"><button class="btn btn-dark">View</button></a></div>
                    </li>
                {% else %}
                <p><em>No Notifications</em></p>
                {% endif %}
                {% endfor %}
                </ul>
        {% else %}
        <p><em>No Notifications</em></p>
        {% endif %}
    </div>
    

{% endblock %}